version: '2'
services:

  facilemanager:
    build:
      context: .
      dockerfile: ./build-facilemanager/Dockerfile
    hostname: ${fm_URL}
    container_name: facilemanager
    networks:
      - frontend
      - backend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 80:80
      - 443:443
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    networks:
      - backend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./mysql-data:/var/lib/mysql
    #ports:
    #  - 3306:3306
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


  fmdns:
    build:
      context: .
      dockerfile: ./build-fmdns/Dockerfile
    hostname: ${fmDNS_URL}
    container_name: fmdns
    networks:
      - frontend
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    #  - ./fmdns-log:/var/log/bind
    ports:
      - ${HOST_IP}:53:53/udp
      - ${HOST_IP}:53:53/tcp
    #  - 8053:80
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      FACILE_MANAGER_HOST: ${fmDNS_Manager}
      FACILE_CLIENT_SERIAL_NUMBER: ${fmDNS_Serial}

networks:
    frontend:
    backend:
