log:
#  level: DEBUG
  filePath: /logs/traefik.log
  format: json

accessLog:
  filePath: /logs/access.log
  format: json

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
#    http:
#      redirections:
#          entryPoint:
#            to: https
#            scheme: https
  websecure:
    address: ":443"

  webalt:
    address: ":8080"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    useBindPortIP: true
#  file:
#    directory: /etc/traefik/dynamic
#    watch: true

certificatesResolvers:
  resolver-http:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      email: "certs@mors.io"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web

#  resolver-https:
#    # Enable ACME (Let's Encrypt): automatic SSL.
#    acme:
#      email: "certs@mors.io"
#      storage: "/letsencrypt/acme-https.json"
#      tlsChallenge: {}
